import { ICONS } from 'assets/icons';
import { images } from '../../../assets/images/index';

export const dashboardData = [
  {
    id: 1,
    title: 'Brand Name',
    content: `Your brand name isn't just a label – it's the heartbeat of your venture. It's the name that'll be on everyone's lips, the name that will inspire curiosity and recognition. Think of it as your invitation to connect with your audience in a memorable way. So, what's in a name? Everything!`,
    image: ICONS.brandNameIcon,
    navLink: 'Learn More',
    image1: ICONS.learnMoreIcon,
  },
  {
    id: 2,
    title: 'Brand Category',
    content: `Your brand category is your compass, guiding you towards your audience's heart. Are you a trendsetting tech startup or a lifestyle trailblazer? Defining your category isn't just about putting a label – it's about finding your tribe. It's the secret sauce that will make your brand irresistible.`,
    image: ICONS.brandCategoryIcon,
    navLink: 'Learn More',
    image1: ICONS.learnMoreIcon,
  },
  {
    id: 3,
    title: 'Brand Logo',
    content: `Your brand logo is your masterpiece. It's the visual cue that'll make heads turn and leave an indelible mark. Colors, shapes, and symbols – they all whisper your brand's story. Design it with confidence, for it's the first impression that lasts.`,
    image: ICONS.brandLogoIcon,
    navLink: 'Learn More',
    image1: ICONS.learnMoreIcon,
  },
];

export const dashboardCard = [
  {
    title: 'Gochew Grill',
    content: '(SEO - Friendly)',
    siteIcon: ICONS.globalIcon,
    siteLink: 'gochewgrill.com',
    channelName: '@gochewgrill',
    channelIcon: ICONS.twitterIcon,
  },
  {
    title: 'Gochew Grill',
    content: '(SEO - Friendly)',
    siteIcon: ICONS.globalIcon,
    siteLink: 'gochewgrill.com',
    channelName: '@gochewgrill',
    channelIcon: ICONS.twitterIcon,
  },
  {
    title: 'Gochew Grill',
    content: '(SEO - Friendly)',
    siteIcon: ICONS.globalIcon,
    siteLink: 'gochewgrill.com',
    channelName: '@gochewgrill',
    channelIcon: ICONS.twitterIcon,
  },
  {
    title: 'Gochew Grill',
    content: '(SEO - Friendly)',
    siteIcon: ICONS.globalIcon,
    siteLink: 'gochewgrill.com',
    channelName: '@gochewgrill',
    channelIcon: ICONS.twitterIcon,
  },
  {
    title: 'Gochew Grill',
    content: '(SEO - Friendly)',
    siteIcon: ICONS.globalIcon,
    siteLink: 'gochewgrill.com',
    channelName: '@gochewgrill',
    channelIcon: ICONS.twitterIcon,
  },
];

export const channelName = [
  { id: 1, image: images.optimizationSettingIcon, title: '0' },
  {
    id: 2,
    image: images.userprofileIcon,
    title: '0',
  },
  {
    id: 3,
    image: images.likeIcon,
    title: '0',
  },
  {
    id: 4,
    image: images.performanceIcon,
    title: '0',
  },
];

export const pageFeatures = [
  {
    id: 1,
    image: images.profilePictureIcon,
    title: 'Profile Picture',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#ED4F9D ',
  },
  {
    id: 2,
    image: images.coverPhotoIcon,
    title: 'Cover photo',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#6366F1',
  },
  {
    id: 3,
    image: images.whatsappIcon,
    title: 'Link WhatsApp',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#25C277',
  },
  {
    id: 4,
    image: images.websiteIcon,
    title: 'Website',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#4AACEA',
  },
  {
    id: 5,
    image: images.locationIcon,
    title: 'Location Info',
    label: 'Done',
    buttonColor: '#25C277',
  },
  { id: 6, image: images.phoneIcon, title: 'Phone number', label: 'Done', buttonColor: '#25C277' },
];
export const businessFeatures = [
  {
    id: 1,
    image: images.websiteIcon,
    title: 'Website',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#4AACEA',
  },
  {
    id: 2,
    image: images.businessAddressIcon,
    title: 'Business address',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#F6A723',
  },
  {
    id: 3,
    image: images.whatsappIcon,
    title: 'WhatsApp business',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#25C277',
  },
  {
    id: 4,
    image: images.phoneIcon,
    title: 'Phone number',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#F472B6',
  },
];

export const linkedinPageFeatures = [
  {
    id: 1,
    image: images.profilePictureIcon,
    title: 'Profile Picture',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#ED4F9D',
  },
  {
    id: 2,
    image: images.coverPhotoIcon,
    title: 'Cover photo',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#6366F1',
  },
  {
    id: 3,
    image: images.websiteIcon,
    title: 'Industry',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#4AACEA',
  },
  {
    id: 4,
    image: images.companySite,
    title: 'Company Size',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#967AD4',
  },
  {
    id: 5,
    image: images.websiteIcon,
    title: 'Website url',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#4AACEA',
  },
  {
    id: 6,
    image: images.hashtag,
    title: 'Hashtags',
    label: 'Add Now',
    content: 'Skip',
    buttonColor: '#F6A723',
  },
  {
    id: 7,
    image: images.description,
    title: 'Description',
    label: 'Add Now',
    content: 'Skip',
    buttonColor: '#967AD4',
  },
  {
    id: 8,
    image: images.inviteFriends,
    title: 'Invite Friends',
    label: 'Add Now',
    content: 'Skip',
    buttonColor: '#ED4F9D',
  },
  {
    id: 9,
    image: images.cutomButton,
    title: 'Custom Button',
    label: 'Add Now',
    content: 'Skip',
    buttonColor: '#25C277',
  },
  {
    id: 10,
    image: images.commitments,
    title: 'Commitments',
    label: 'Add Now',
    content: 'Skip',
    buttonColor: '#4AACEA',
  },
];

export const linkedinProfileFeatures = [
  {
    id: 1,
    image: images.profilePictureIcon,
    title: 'Profile Name',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#ED4F9D',
  },
  {
    id: 2,
    image: images.coverPhotoIcon,
    title: 'Cover image',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#6366F1',
  },
  {
    id: 3,
    image: images.websiteIcon,
    title: 'Headline',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#4AACEA',
  },
  {
    id: 4,
    image: images.education,
    title: 'Education Detail',
    label: 'Add Now',
    content: 'Skip',
    buttonColor: '#25C277',
  },
  {
    id: 5,
    image: images.work,
    title: 'Work Experience',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#4AACEA',
  },
  {
    id: 6,
    image: images.creator,
    title: 'Creator Mode',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#ED4F9D',
  },
  {
    id: 7,
    image: images.followers,
    title: 'Followers',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#F6A723',
  },
  {
    id: 8,
    image: images.connection,
    title: 'Connection',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#8B5CF6',
  },
  {
    id: 9,
    image: images.content,
    title: 'Content Posting',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#25C277',
  },
  {
    id: 10,
    image: images.interests,
    title: 'Interests',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#8B5CF6',
  },
  {
    id: 11,
    image: images.certification,
    title: 'Certification',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#F6A723',
  },
  {
    id: 12,
    image: images.profilePictureIcon,
    title: 'Profile url',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#ED4F9D',
  },
];

export const pinterestFeatures = [
  {
    id: 1,
    image: images.profilePictureIcon,
    title: 'Profile Picture',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#ED4F9D',
  },
  {
    id: 2,
    image: images.description,
    title: 'Description',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#8B5CF6',
  },
  {
    id: 3,
    image: images.websiteIcon,
    title: 'Website url',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#4AACEA',
  },
  {
    id: 4,
    image: images.email,
    title: 'Email',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#F96056',
  },
  {
    id: 5,
    image: images.phoneIcon,
    title: 'Phone number',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#F472B6',
  },
  {
    id: 6,
    image: images.setupBusiness,
    title: 'Setup business goals',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#25C277',
  },
  {
    id: 7,
    image: images.profileVisiblity,
    title: 'Profile visibility ',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#6366F1',
  },
  {
    id: 8,
    image: images.followers,
    title: 'Followers',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#F6A723',
  },
  {
    id: 9,
    image: images.monthlyViews,
    title: 'Monthly views',
    content: 'Skip',
    label: 'Add Now',
    buttonColor: '#8B5CF6',
  },
];
